# 1. Create and inspect an array
**Create a numpy array of shape (3,4) filled with random integers from 0 to 9 print its shape size and data type** 

In [25]:
import numpy as np
x=np.random.randint(0,10,size=(3,4))
print(f'''{x} shape of x {x.shape}\n
      Min along rows {x.min(axis=0)}''')


[[2 0 4 4]
 [2 6 6 3]
 [2 0 7 8]] shape of x (3, 4)

      Min along rows [2 0 4 3]


# 2. Replace all even numbers with masking 
Given array of [1,2,3,4,5,6] replace even numbers with -1 using maksing

In [27]:
#np.where is used to achieve this, in this a terniary operator can be used to access the value and
# conditionally values can be set
x= np.array([1,2,3,4,5,6])
np.where(x%2 ==1,x, -1)

array([ 1, -1,  3, -1,  5, -1])

# 3. Extract borders of a matrix
Create a 5 * 5 array of ones, replace all the values inside with 0 , so that borders only remain as 1

In [44]:
# This uses array slicing tecnique sequence[start:stop:step]
x=np.ones(25, dtype="int32").reshape(5,5)
x[1:4,1:4]=0
x

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

# 4. Normalizing an array
Given 1D array, normalize it to have values between 1 and 0 using normx= x-min(x)/max(x)-min(x)

In [ ]:
x=np.arange(start=1, stop=10)
normX=(x-min(x))/(max(x)-min(x))
normX

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

# 5. Compute Row wise and column wise means   
Crearte a 4 * 4 array and compute row wise and column wise means

In [60]:
# For this we have axis
x=np.arange(16).reshape(4,4)
print(f''' Row wise mean {x.mean(axis=1)}, Column wise mean {x.mean(axis=0)} ''')


 Row wise mean [ 1.5  5.5  9.5 13.5], Column wise mean [6. 7. 8. 9.] 


# 6. Reverse an array with slicing only no loops

In [68]:
# ::-1 is used to reverse an array
x= np.arange(10)
revX= x[::-1]
print(f''' {x} and {revX}''')

 [0 1 2 3 4 5 6 7 8 9] and [9 8 7 6 5 4 3 2 1 0]


# 7. Finding the most frequent value
Using mode

In [ ]:
#This is showing only one mode, numpy doesn't tech have a built in mode operator
from scipy import stats
np.random.seed(12)
x= np.random.randint(size=10,low=0,high=10)
mode = stats.mode(x, keepdims=True)
print(f''' The mode {np.sort(x)} of is {mode.mode[0]}''')
for val in mode.mode:
    print(val)


 The mode [0 1 1 2 3 3 4 5 6 6] of is 1
1


In [108]:
 #Conditional replacement with np.where
x= np.random.randint(low=15,high=50,size=(10))
labels =np.where(x<25,"cold",'hot')
print(x,'\n', labels)


[34 23 41 23 37 29 19 40 30 19] 
 ['hot' 'cold' 'hot' 'cold' 'hot' 'hot' 'cold' 'hot' 'hot' 'cold']
